# Generated by Django 4.1.2 on 2022-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_user_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_books',
            name='books_count',
            field=models.IntegerField(default=0),
        ),
    ]
